### ISSUE TITLE
请教关于Hub Clients map 

### ISSUE THREAD

**Issue by isensen** [MQEnergy/go-websocket#2]
go的初学者,有个疑问,能否请教一下
`type Hub struct {
	Clients       map[*Client]bool 
	....`
	
Hub 的Clients   key是 \*Client类型, value是个bool类型, 我看[gorilla websocket chat example](https://github.com/gorilla/websocket/blob/main/examples/chat/hub.go)也是这样做的, 但是它是没有相关单客户推送的需求. 这是作者实现的[单客户推送](https://github.com/MQEnergy/go-websocket/blob/5769a7785ca276ae39905bb163f53830d5e64a7c/client_hub.go#L148) 是需要循环比对去取*Client,为什么不直接使用 map[int] *Client类型呢, key直接是snowflake产生的id, 还是经过权衡是原方式更有性能优势 ?

**Comment by chenxi2015** [comment]
通过雪花算法生成id 也是需要时间的，直接用bool能解决问题，为什么不呢？

**Comment by isensen** [comment]
> 通过雪花算法生成id 也是需要时间的，直接用bool能解决问题，为什么不呢？

不好意思,可能我没表达清楚, 连接时雪花算法生成id 不是已经存入clientid 了吗?存储的时候为什么不使用clientid做为key, value可以存储 *Client,这样单播时, 在取出对应client时, 这样不用循环比对了, 直接通过clientId取出来不更方便吗? 是有别的考虑吗?

**Comment by chenxi2015** [comment]
你说的应该是这一块代码吧 
<img width="525" alt="image" src="https://github.com/MQEnergy/go-websocket/assets/13269485/91578fb7-581a-41a2-8125-cfd5edff7c7e">
这一块代码是要优化，如果客户端多了 会有性能影响。你的想法可行 感谢。

**Comment by isensen** [comment]
> 你说的应该是这一块代码吧 <img alt="image" width="525" src="https://private-user-images.githubusercontent.com/13269485/325216189-91578fb7-581a-41a2-8125-cfd5edff7c7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwMDc3MTcsIm5iZiI6MTcxNDAwNzQxNywicGF0aCI6Ii8xMzI2OTQ4NS8zMjUyMTYxODktOTE1NzhmYjctNTgxYS00MWEyLTgxMjUtY2ZkNWVkZmY3YzdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI1VDAxMTAxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhMDZhZWVhNDcyMWI0MWMzNGMzMTgyOGVmOTgzODlkY2JiMGQ5YzUzMmU2Nzc4MTNlMzc5MTk5ZmE3YjZhNDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Z5JP-U_N_VPqh-9v8mCtX-Mgok__raeE4ukf377vkb4"> 这一块代码是要优化，如果客户端多了 会有性能影响。你的想法可行 感谢。

感谢解惑,我是初学, 看你代码学到很多
